### PR TITLE
Setup Maths Magicians Project

### PR DESCRIPTION
**Pull request by lily4178993**
# Setup Maths Magicians Project

## Description
This pull request sets up the initial environment and tools needed to develop the Maths Magicians React application. It includes various commits to initialize the project, fix linter errors, and add essential files and content.

## Checklist
- [x] Initial project setup
- [x] Fixed linter errors
- [x] Added public icons and description
- [x] Added README content
- [x] Added README logo

## Reviewer Notes
Please review the changes made to ensure that the project setup is correct, linter errors are resolved, and the README contains the necessary content.

## How to Test
To test these changes locally, follow these steps:

1. Clone the repository:
   ```bash
   git clone https://github.com/lily4178993/maths-magicians.git
   ```

2. Navigate to the project directory:
  ```bash
    cd maths-magicians
  ```

3. Install project dependencies:
  ```bash
    npm install
  ```

4. Start the development server:
  ```bash
    npm start
  ```

5. Open your web browser and access the application at `http://localhost:3000`.

---

_This pull request is part of the ongoing development process for the Maths Magicians project._

### CODE REVIEW

**Review by AbelG101 — COMMENTED** [review]
# Hi @lily4178993 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- I noticed you removed the "Future features" section from the readme please take note that the only optional sections that can be removed are the "FAQ" and sometimes the "Live demo" section (if the project requirement doesn't require it to be deployed). So I'd suggest you restore the section and write at least 1 feature that'll be added in the future.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by lily4178993** [comment]
## Updates

Changes implemented in the README file:

- Add **_Future Features_**
- Remove **_Live Demo_**

**Review by DammyShittu — APPROVED** [review]
Hi @lily4178993,

## APPROVED 🟢

## Highlights
✔️ CRA react app

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lily4178993** [comment]
Thank you all for reviewing this pull request.

**Pull request merged**
